controller:
  replicaCount: 1
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
  nodeSelector:
    kubernetes.io/os: "linux"
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      nodeSelector:
        kubernetes.io/os: "linux"
  ingressClass: "nginx"
  ingressClassResource:
    default: true
    name: "nginx"
    enabled: true
    controllerValue: "k8s.io/ingress-nginx"
  watchIngressWithoutClass: true
  settings:
    {{- range $key, $value := .Values.settings }}
    {{$key}}: {{$value}}
    {{- end }}

defaultBackend:
  nodeSelector:
    kubernetes.io/os: "linux"
